// ============================================================================
// DNA Templates — الجينات الثابتة لكل نوع فقاعة
// ============================================================================

import { BubbleType } from './types';
import type { BubbleGene } from './types';

export const DNA_TEMPLATES: Record<string, BubbleGene> = {
  [BubbleType.FOOD]: {
    id: 'dna-food',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(255, 215, 64, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover-gold',
    glowColor: '#FFD740',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FFD740', '#FF6B00'],
    glassOpacity: 0.15,
    rimIntensity: 0.5,
  },
  [BubbleType.RESTAURANT]: {
    id: 'dna-restaurant',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(255, 152, 0, 0.2)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover',
    glowColor: '#FF9800',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FF9800', '#FFD54F'],
    glassOpacity: 0.18,
    rimIntensity: 0.55,
  },
  [BubbleType.JOB]: {
    id: 'dna-job',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(255, 110, 64, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover-electric',
    glowColor: '#FF6E40',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FF6E40', '#FF1744'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
  [BubbleType.RECRUITMENT]: {
    id: 'dna-recruitment',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(0, 150, 136, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-secure',
    animationHover: 'bubble-hover',
    glowColor: '#009688',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#009688', '#4DB6AC'],
    glassOpacity: 0.14,
    rimIntensity: 0.5,
  },
  [BubbleType.PAYMENT]: {
    id: 'dna-payment',
    borderRadius: '50%',
    backdropBlur: '24px',
    borderColor: 'rgba(0, 230, 118, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-secure',
    animationHover: 'bubble-hover-secure',
    glowColor: '#00E676',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#00E676', '#69F0AE'],
    glassOpacity: 0.16,
    rimIntensity: 0.6,
  },
  [BubbleType.WALLET]: {
    id: 'dna-wallet',
    borderRadius: '50%',
    backdropBlur: '24px',
    borderColor: 'rgba(0, 200, 150, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-secure',
    animationHover: 'bubble-hover',
    glowColor: '#00c896',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#00c896', '#00d4ff'],
    glassOpacity: 0.15,
    rimIntensity: 0.5,
  },
  [BubbleType.EMERGENCY]: {
    id: 'dna-emergency',
    borderRadius: '50%',
    backdropBlur: '28px',
    borderColor: 'rgba(255, 23, 68, 0.25)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-pulse',
    animationHover: 'bubble-hover-pulse',
    glowColor: '#FF1744',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FF1744', '#F50057'],
    glassOpacity: 0.2,
    rimIntensity: 0.7,
  },
  [BubbleType.PLATFORM]: {
    id: 'dna-platform',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(100, 255, 218, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover-electric',
    glowColor: '#64FFDA',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#64FFDA', '#00BFA5'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
  [BubbleType.NEGOTIATION]: {
    id: 'dna-negotiation',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(255, 215, 64, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover-gold',
    glowColor: '#FFD740',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FFD740', '#FF6D00'],
    glassOpacity: 0.14,
    rimIntensity: 0.5,
  },
  [BubbleType.PRODUCT]: {
    id: 'dna-product',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(68, 138, 255, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#448AFF',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#448AFF', '#82B1FF'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
  [BubbleType.SERVICE]: {
    id: 'dna-service',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(171, 71, 188, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#AB47BC',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#AB47BC', '#CE93D8'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
  [BubbleType.CHAT]: {
    id: 'dna-chat',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(168, 85, 247, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover-electric',
    glowColor: '#a855f7',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#a855f7', '#ec4899'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
  [BubbleType.SUBCHAT]: {
    id: 'dna-subchat',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(168, 85, 247, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#a855f7',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#a855f7', '#ec4899'],
    glassOpacity: 0.14,
    rimIntensity: 0.48,
  },
  [BubbleType.DASHBOARD]: {
    id: 'dna-dashboard',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(0, 212, 255, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover-electric',
    glowColor: '#00d4ff',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#00d4ff', '#4a9eff'],
    glassOpacity: 0.12,
    rimIntensity: 0.5,
  },
  [BubbleType.AD]: {
    id: 'dna-ad',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(255, 152, 0, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover',
    glowColor: '#FF9800',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FF9800', '#FFB74D'],
    glassOpacity: 0.14,
    rimIntensity: 0.48,
  },
  [BubbleType.ADS]: {
    id: 'dna-ads',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(255, 107, 0, 0.2)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover',
    glowColor: '#FF6B00',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#FF6B00', '#FFD700'],
    glassOpacity: 0.16,
    rimIntensity: 0.52,
  },
  [BubbleType.ANALYTICS]: {
    id: 'dna-analytics',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(236, 72, 153, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#ec4899',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#ec4899', '#a855f7'],
    glassOpacity: 0.13,
    rimIntensity: 0.47,
  },
  [BubbleType.SUGGESTIONS]: {
    id: 'dna-suggestions',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(0, 212, 255, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#00d4ff',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#00d4ff', '#4a9eff'],
    glassOpacity: 0.13,
    rimIntensity: 0.47,
  },
  [BubbleType.SETTINGS]: {
    id: 'dna-settings',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(148, 163, 184, 0.15)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-secure',
    animationHover: 'bubble-hover',
    glowColor: '#94a3b8',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#94a3b8', '#cbd5e1'],
    glassOpacity: 0.1,
    rimIntensity: 0.4,
  },
  [BubbleType.PHARMACY]: {
    id: 'dna-pharmacy',
    borderRadius: '50%',
    backdropBlur: '24px',
    borderColor: 'rgba(0, 200, 83, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-secure',
    animationHover: 'bubble-hover-secure',
    glowColor: '#00C853',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#00C853', '#69F0AE'],
    glassOpacity: 0.15,
    rimIntensity: 0.5,
  },
  [BubbleType.FASHION]: {
    id: 'dna-fashion',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(244, 143, 177, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#F48FB1',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#F48FB1', '#F8BBD0'],
    glassOpacity: 0.13,
    rimIntensity: 0.45,
  },
  [BubbleType.GROCERY]: {
    id: 'dna-grocery',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(121, 85, 72, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-gold',
    animationHover: 'bubble-hover',
    glowColor: '#795548',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#795548', '#A1887F'],
    glassOpacity: 0.14,
    rimIntensity: 0.48,
  },
  [BubbleType.DELIVERY]: {
    id: 'dna-delivery',
    borderRadius: '50%',
    backdropBlur: '22px',
    borderColor: 'rgba(3, 169, 244, 0.18)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover-electric',
    glowColor: '#03A9F4',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#03A9F4', '#4FC3F7'],
    glassOpacity: 0.14,
    rimIntensity: 0.5,
  },
  [BubbleType.GENERIC]: {
    id: 'dna-generic',
    borderRadius: '50%',
    backdropBlur: '20px',
    borderColor: 'rgba(100, 180, 255, 0.12)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    animationIn: 'bubble-in-electric',
    animationHover: 'bubble-hover',
    glowColor: '#64b4ff',
    fontFamily: 'Noto Sans Arabic',
    dir: 'rtl',
    colors: ['#64b4ff', '#a78bfa'],
    glassOpacity: 0.12,
    rimIntensity: 0.45,
  },
};

/** Get DNA template for a bubble type */
export function getDNA(type: BubbleType): BubbleGene {
  return DNA_TEMPLATES[type] || DNA_TEMPLATES[BubbleType.GENERIC];
}
